[global]

[logger]

[client]
toolbarMode = "minimal"

[runner]

[server]
#address = "www.data.eona-x.eu"
baseUrlPath = "ontology-visual-tool"

[browser]
#serverPort = 850
gatherUsageStats = false

[mapbox]

[theme]
primaryColor="#5681d0"
backgroundColor="#212750"
secondaryBackgroundColor="#1a1a3d"
textColor="#f8f8f2"
